apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ketch-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: ketch/overlays/production
    repoURL: https://github.com/devopsparadox/ketch-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

