apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: devops-toolkit/staging
    repoURL: https://github.com/devopsparadox/ketch-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

